### ISSUE TITLE
test,datasets

### ISSUE THREAD

**Issue by wudami** [Jzy2017/TRIS#2]
Hello, regarding the code you provided, I have the following questions for you:

(1) How should I modify the code for the dataset path?

(2) Also, you've used the datasets UDIS-D and MS-COCO. Under which path should I place them? Are there any naming requirements?

(3) In ImageAlignment/test.py, there's a reference to "Image_UDIS". Could you please tell me in which .py file Image_UDIS is defined? I couldn't find it and I'm getting an error.

(4) In lines 105-114 of ImageAlignment/test.py, the variable "attack" is throwing an error, indicating an unresolved reference.

**Comment by wudami** [comment]
![009EC6785E7624EE4608B19C4995CF7D](https://github.com/Jzy2017/TRIS/assets/154413680/ce696b62-08b7-4407-8ce7-66cebe68b183)
![EFDC00AC1334B77B61CE3610E5D1B049](https://github.com/Jzy2017/TRIS/assets/154413680/bf6ba00a-2e28-4061-bb6e-4a135f8724e5)

**Comment by szgy66** [comment]
> Hello, regarding the code you provided, I have the following questions for you:
> 
> (1) How should I modify the code for the dataset path?
> 
> (2) Also, you've used the datasets UDIS-D and MS-COCO. Under which path should I place them? Are there any naming requirements?
> 
> (3) In ImageAlignment/test.py, there's a reference to "Image_UDIS". Could you please tell me in which .py file Image_UDIS is defined? I couldn't find it and I'm getting an error.
> 
> (4) In lines 105-114 of ImageAlignment/test.py, the variable "attack" is throwing an error, indicating an unresolved reference.

Had you solve it? The class Image_UDIS hadn't be  definited

**Comment by Jzy2017** [comment]
I have provided a dataset code for open source use. For dataset issues, users can modify the data and data root paths to replace their own datasets. For the choice of attack method, I changed it to the default attack method.
